[project]
name = "black-scholes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib[pyplot]>=3.10.5",
    "seaborn>=0.13.2",
    "streamlit[charts]>=1.48.1",
]
